
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.Goose_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "DataSequence" ) ]
    public class DataSequence : IASN1PreparedElement {

	    private System.Collections.Generic.ICollection<Data> val = null; 
            
            
            [ASN1SequenceOf( Name = "DataSequence", IsSetOf = false) ]

            public System.Collections.Generic.ICollection<Data> Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public void initValue() {
                this.Value = new System.Collections.Generic.List<Data>();
            }
            
            public void Add(Data item) {
                this.Value.Add(item);
            }

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DataSequence));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
