
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.Goose_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Choice ( Name = "GOOSE") ]
    public class GOOSE : IASN1PreparedElement {
                    
        
	private GoosePdu goosePdu_ ;
        private bool  goosePdu_selected = false ;
        
                
        
        [ASN1Element ( Name = "goosePdu", IsOptional =  false , HasTag =  true, Tag = 1, 
        TagClass =  TagClasses.Application  , HasDefaultValue =  false )  ]
    
        public GoosePdu GoosePdu
        {
            get { return goosePdu_; }
            set { selectGoosePdu(value); }
        }
        
                
          
        public bool isGoosePduSelected () {
            return this.goosePdu_selected ;
        }

        


        public void selectGoosePdu (GoosePdu val) {
            this.goosePdu_ = val;
            this.goosePdu_selected = true;
            
                        
        }
        
  

            public void initWithDefaults()
	    {
	    }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(GOOSE));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
