
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn.attributes;

namespace BISC.Modules.Connection.MMS.Goose_ASN1_Model {

        [ASN1Module ( Name = "IEC61850", IsImplicitTags =  false  ) ]
        public class IEC61850 {
        }
        
}
