
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "AcknowledgeEventNotification_Request", IsSet = false  )]
    public class AcknowledgeEventNotification_Request : IASN1PreparedElement {
                    
	private ObjectName eventEnrollmentName_ ;
	
        [ASN1Element ( Name = "eventEnrollmentName", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public ObjectName EventEnrollmentName
        {
            get { return eventEnrollmentName_; }
            set { eventEnrollmentName_ = value;  }
        }
        
                
          
	private EC_State acknowledgedState_ ;
	
        [ASN1Element ( Name = "acknowledgedState", IsOptional =  false , HasTag =  true, Tag = 2 , HasDefaultValue =  false )  ]
    
        public EC_State AcknowledgedState
        {
            get { return acknowledgedState_; }
            set { acknowledgedState_ = value;  }
        }
        
                
          
	private EventTime timeOfAcknowledgedTransition_ ;
	
        [ASN1Element ( Name = "timeOfAcknowledgedTransition", IsOptional =  false , HasTag =  true, Tag = 3 , HasDefaultValue =  false )  ]
    
        public EventTime TimeOfAcknowledgedTransition
        {
            get { return timeOfAcknowledgedTransition_; }
            set { timeOfAcknowledgedTransition_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(AcknowledgeEventNotification_Request));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
