
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "CS_CreateProgramInvocation_Request" )]
    public class CS_CreateProgramInvocation_Request: IASN1PreparedElement {
    
            private long val;
            
            [ASN1Integer( Name = "CS-CreateProgramInvocation-Request" )]
            
            public long Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public CS_CreateProgramInvocation_Request() {
            }

            public CS_CreateProgramInvocation_Request(long value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(CS_CreateProgramInvocation_Request));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
