
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "DefineEventEnrollment_Error") ]
    public class DefineEventEnrollment_Error: IASN1PreparedElement {
            
           
        private ObjectName  val;

        
        [ASN1Element ( Name = "DefineEventEnrollment-Error", IsOptional =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public ObjectName Value
        {
                get { return val; }        
                    
                set { val = value; }
                        
        }            

                    
        
        public DefineEventEnrollment_Error ()
        {
        }

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DefineEventEnrollment_Error));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

        
    }
            
}
