
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "DefineNamedType_Request", IsSet = false  )]
    public class DefineNamedType_Request : IASN1PreparedElement {
                    
	private ObjectName typeName_ ;
	
        [ASN1Element ( Name = "typeName", IsOptional =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public ObjectName TypeName
        {
            get { return typeName_; }
            set { typeName_ = value;  }
        }
        
                
          
	private TypeSpecification typeSpecification_ ;
	
        [ASN1Element ( Name = "typeSpecification", IsOptional =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public TypeSpecification TypeSpecification
        {
            get { return typeSpecification_; }
            set { typeSpecification_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DefineNamedType_Request));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
