
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "DeleteNamedVariableList_Response", IsSet = false  )]
    public class DeleteNamedVariableList_Response : IASN1PreparedElement {
                    
	private Unsigned32 numberMatched_ ;
	
        [ASN1Element ( Name = "numberMatched", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public Unsigned32 NumberMatched
        {
            get { return numberMatched_; }
            set { numberMatched_ = value;  }
        }
        
                
          
	private Unsigned32 numberDeleted_ ;
	
        [ASN1Element ( Name = "numberDeleted", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public Unsigned32 NumberDeleted
        {
            get { return numberDeleted_; }
            set { numberDeleted_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DeleteNamedVariableList_Response));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
