
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "ExchangeData_Request", IsSet = false  )]
    public class ExchangeData_Request : IASN1PreparedElement {
                    
	private ObjectName dataExchangeName_ ;
	
        [ASN1Element ( Name = "dataExchangeName", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public ObjectName DataExchangeName
        {
            get { return dataExchangeName_; }
            set { dataExchangeName_ = value;  }
        }
        
                
          
	private System.Collections.Generic.ICollection<Data> listOfRequestData_ ;
	
[ASN1SequenceOf( Name = "listOfRequestData", IsSetOf = false  )]

    
        [ASN1Element ( Name = "listOfRequestData", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public System.Collections.Generic.ICollection<Data> ListOfRequestData
        {
            get { return listOfRequestData_; }
            set { listOfRequestData_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ExchangeData_Request));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
