
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "FileName" ) ]
    public class FileName : IASN1PreparedElement {

	    private System.Collections.Generic.ICollection<string> val = null; 
            
            [ASN1String( Name = "", StringType =  UniversalTags.GraphicString , IsUCS = false )]
            [ASN1SequenceOf( Name = "FileName", IsSetOf = false) ]
        //[ASN1Element(Name = "FileName", IsOptional = false, HasTag = true, Tag = 0, HasDefaultValue = false, IsImplicitTag = true)]
        public System.Collections.Generic.ICollection<string> Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public void initValue() {
                this.Value = new System.Collections.Generic.List<string>();
            }
            
            public void Add(string item) {
                this.Value.Add(item);
            }

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(FileName));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
