
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "GetEventEnrollmentAttributes_Response", IsSet = false  )]
    public class GetEventEnrollmentAttributes_Response : IASN1PreparedElement {
                    
	private System.Collections.Generic.ICollection<EEAttributes> listOfEEAttributes_ ;
	
[ASN1SequenceOf( Name = "listOfEEAttributes", IsSetOf = false  )]

    
        [ASN1Element ( Name = "listOfEEAttributes", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public System.Collections.Generic.ICollection<EEAttributes> ListOfEEAttributes
        {
            get { return listOfEEAttributes_; }
            set { listOfEEAttributes_ = value;  }
        }
        
                
          
	private bool moreFollows_ ;
	[ASN1Boolean( Name = "" )]
    
        [ASN1Element ( Name = "moreFollows", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  true )  ]
    
        public bool MoreFollows
        {
            get { return moreFollows_; }
            set { moreFollows_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	bool param_MoreFollows =
            false;
        MoreFollows = param_MoreFollows;
    
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(GetEventEnrollmentAttributes_Response));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
