
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model
{


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "GetNameList_Response", IsSet = false)]
    public class GetNameList_Response : IASN1PreparedElement
    {

        private System.Collections.Generic.ICollection<Identifier> listOfIdentifier_;

        [ASN1SequenceOf(Name = "listOfIdentifier", IsSetOf = false)]


        [ASN1Element(Name = "listOfIdentifier", IsOptional = false, HasTag = true, Tag = 0, HasDefaultValue = false)]

        public System.Collections.Generic.ICollection<Identifier> ListOfIdentifier
        {
            get { return listOfIdentifier_; }
            set { listOfIdentifier_ = value; }
        }



        private bool moreFollows_;
        [ASN1Boolean(Name = "")]

        [ASN1Element(Name = "moreFollows", IsOptional = false, HasTag = true, Tag = 1, HasDefaultValue = true)]

        public bool MoreFollows
        {
            get { return moreFollows_; }
            set { moreFollows_ = value; }
        }




        public void initWithDefaults()
        {
            bool param_MoreFollows =
        true;
            MoreFollows = param_MoreFollows;

        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(GetNameList_Response));
        public IASN1PreparedElementData PreparedData
        {
            get { return preparedData; }
        }


    }

}
