
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model
{


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "InformationReport", IsSet = false)]
    public class InformationReport : IASN1PreparedElement
    {

        private VariableAccessSpecification variableAccessSpecification_;

        [ASN1Element(Name = "variableAccessSpecification", IsOptional = false, HasTag = false, HasDefaultValue = false)]

        public VariableAccessSpecification VariableAccessSpecification
        {
            get { return variableAccessSpecification_; }
            set { variableAccessSpecification_ = value; }
        }



        private System.Collections.Generic.ICollection<AccessResult> listOfAccessResult_;

        [ASN1SequenceOf(Name = "listOfAccessResult", IsSetOf = false)]


        [ASN1Element(Name = "listOfAccessResult", IsOptional = false, HasTag = true, Tag = 0, HasDefaultValue = false)]

        public System.Collections.Generic.ICollection<AccessResult> ListOfAccessResult
        {
            get { return listOfAccessResult_; }
            set { listOfAccessResult_ = value; }
        }




        public void initWithDefaults()
        {

        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(InformationReport));
        public IASN1PreparedElementData PreparedData
        {
            get { return preparedData; }
        }


    }

}
