
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "InitiateUploadSequence_Response", IsSet = false  )]
    public class InitiateUploadSequence_Response : IASN1PreparedElement {
                    
	private Integer32 ulsmID_ ;
	
        [ASN1Element ( Name = "ulsmID", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public Integer32 UlsmID
        {
            get { return ulsmID_; }
            set { ulsmID_ = value;  }
        }
        
                
          
	private System.Collections.Generic.ICollection<MMSString> listOfCapabilities_ ;
	
[ASN1SequenceOf( Name = "listOfCapabilities", IsSetOf = false  )]

    
        [ASN1Element ( Name = "listOfCapabilities", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public System.Collections.Generic.ICollection<MMSString> ListOfCapabilities
        {
            get { return listOfCapabilities_; }
            set { listOfCapabilities_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(InitiateUploadSequence_Response));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
