
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.attributes.constraints;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "Integer8" )]
    public class Integer8: IASN1PreparedElement {
    
            private int val;
            
            [ASN1Integer( Name = "Integer8" )]
            [ASN1ValueRangeConstraint ( 
		
		Min = -128L, 
		
		Max = 127L 
		
		) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public Integer8() {
            }

            public Integer8(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Integer8));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
