
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.attributes.constraints;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "MMS255String") ]
    public class MMS255String: IASN1PreparedElement {

            private String val;
    
            [ASN1String( Name = "MMS255String", 
        StringType =  UniversalTags.UTF8String , IsUCS = false) ]
            [ASN1ValueRangeConstraint ( 
		
		Min = 1L, 
		
		Max = 255L 
		
		) ]
	    
            public String Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public MMS255String() {
            }

            public MMS255String(String val) {
                this.val = val;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(MMS255String));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
