
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "ModifierStep", IsSet = false  )]
    public class ModifierStep : IASN1PreparedElement {
                    
	private long modifierID_ ;
	[ASN1Integer( Name = "" )]
    
        [ASN1Element ( Name = "modifierID", IsOptional =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public long ModifierID
        {
            get { return modifierID_; }
            set { modifierID_ = value;  }
        }
        
                
          
	private Modifier modifier_ ;
	
        [ASN1Element ( Name = "modifier", IsOptional =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public Modifier Modifier
        {
            get { return modifier_; }
            set { modifier_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ModifierStep));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
