
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model
{


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "ReadJournal_Response", IsSet = false)]
    public class ReadJournal_Response : IASN1PreparedElement
    {

        private System.Collections.Generic.ICollection<JournalEntry> listOfJournalEntry_;

        [ASN1SequenceOf(Name = "listOfJournalEntry", IsSetOf = false)]


        [ASN1Element(Name = "listOfJournalEntry", IsOptional = false, HasTag = true, Tag = 0, HasDefaultValue = false)]

        public System.Collections.Generic.ICollection<JournalEntry> ListOfJournalEntry
        {
            get { return listOfJournalEntry_; }
            set { listOfJournalEntry_ = value; }
        }



        private bool moreFollows_;
        [ASN1Boolean(Name = "")]

        [ASN1Element(Name = "moreFollows", IsOptional = false, HasTag = true, Tag = 1, HasDefaultValue = true)]

        public bool MoreFollows
        {
            get { return moreFollows_; }
            set { moreFollows_ = value; }
        }




        public void initWithDefaults()
        {
            bool param_MoreFollows =
        false;
            MoreFollows = param_MoreFollows;

        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ReadJournal_Response));
        public IASN1PreparedElementData PreparedData
        {
            get { return preparedData; }
        }


    }

}
