
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.coders;
using BISC.Modules.Connection.MMS.org.bn.types;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model
{


    [ASN1PreparedElement]
    [ASN1BoxedType(Name = "TimeOfDay")]
    public class TimeOfDay : IASN1PreparedElement
    {

        private byte[] val = null;

        [ASN1OctetString(Name = "TimeOfDay")]

        //[ASN1SizeConstraint ( Max = 4L )]

        public byte[] Value
        {
            get { return val; }
            set { val = value; }
        }

        public TimeOfDay()
        {
        }

        public TimeOfDay(byte[] value)
        {
            this.Value = value;
        }

        public TimeOfDay(BitString value)
        {
            this.Value = value.Value;
        }

        public void initWithDefaults()
        {
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(TimeOfDay));
        public IASN1PreparedElementData PreparedData
        {
            get { return preparedData; }
        }

    }

}
