
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.attributes.constraints;
using BISC.Modules.Connection.MMS.org.bn.coders;
using BISC.Modules.Connection.MMS.org.bn.types;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "Transitions") ]
    public class Transitions : IASN1PreparedElement {
    
            private BitString val = null;

            [ASN1BitString( Name = "Transitions") ]            
            
            [ASN1SizeConstraint ( Max = 7L )]
        
            public BitString Value
            {
                get { return val; }
                set { val = value; }
            }            
            
            public Transitions() {
            }

            public Transitions(BitString value) {
                this.Value = value;
            }            


            public void initWithDefaults()
	    {
	    }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Transitions));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
