
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model
{


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "UploadSegment_Response", IsSet = false)]
    public class UploadSegment_Response : IASN1PreparedElement
    {

        private LoadData loadData_;

        [ASN1Element(Name = "loadData", IsOptional = false, HasTag = false, HasDefaultValue = false)]

        public LoadData LoadData
        {
            get { return loadData_; }
            set { loadData_ = value; }
        }



        private bool moreFollows_;
        [ASN1Boolean(Name = "")]

        [ASN1Element(Name = "moreFollows", IsOptional = false, HasTag = true, Tag = 1, HasDefaultValue = true)]

        public bool MoreFollows
        {
            get { return moreFollows_; }
            set { moreFollows_ = value; }
        }




        public void initWithDefaults()
        {
            bool param_MoreFollows =
        false;
            MoreFollows = param_MoreFollows;

        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(UploadSegment_Response));
        public IASN1PreparedElementData PreparedData
        {
            get { return preparedData; }
        }


    }

}
