
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "WriteJournal_Request", IsSet = false  )]
    public class WriteJournal_Request : IASN1PreparedElement {
                    
	private ObjectName journalName_ ;
	
        [ASN1Element ( Name = "journalName", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public ObjectName JournalName
        {
            get { return journalName_; }
            set { journalName_ = value;  }
        }
        
                
          
	private System.Collections.Generic.ICollection<EntryContent> listOfJournalEntry_ ;
	
[ASN1SequenceOf( Name = "listOfJournalEntry", IsSetOf = false  )]

    
        [ASN1Element ( Name = "listOfJournalEntry", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public System.Collections.Generic.ICollection<EntryContent> ListOfJournalEntry
        {
            get { return listOfJournalEntry_; }
            set { listOfJournalEntry_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(WriteJournal_Request));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
