
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using BISC.Modules.Connection.MMS.org.bn;
using BISC.Modules.Connection.MMS.org.bn.attributes;
using BISC.Modules.Connection.MMS.org.bn.coders;

namespace BISC.Modules.Connection.MMS.MMS_ASN1_Model {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "Write_Request", IsSet = false  )]
    public class Write_Request : IASN1PreparedElement {
                    
	private VariableAccessSpecification variableAccessSpecification_ ;
	
        [ASN1Element ( Name = "variableAccessSpecification", IsOptional =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public VariableAccessSpecification VariableAccessSpecification
        {
            get { return variableAccessSpecification_; }
            set { variableAccessSpecification_ = value;  }
        }
        
                
          
	private System.Collections.Generic.ICollection<Data> listOfData_ ;
	
[ASN1SequenceOf( Name = "listOfData", IsSetOf = false  )]

    
        [ASN1Element ( Name = "listOfData", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public System.Collections.Generic.ICollection<Data> ListOfData
        {
            get { return listOfData_; }
            set { listOfData_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Write_Request));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
