//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISC.Model.Iec61850Ed2.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BISC.Model.Iec61850Ed2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.iec.ch/61850/2003/SCL&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	xmlns=&quot;http://www.iec.ch/61850/2003/SCL&quot; xmlns:scl=&quot;http://www.iec.ch/61850/2003/SCL&quot; elementFormDefault=&quot;qualified&quot;
        ///	attributeFormDefault=&quot;unqualified&quot; finalDefault=&quot;extension&quot; version=&quot;1.4&quot;&gt;
        ///	&lt;xs:annotation&gt;
        ///		&lt;xs:documentation xml:lang=&quot;en&quot;&gt;COPYRIGHT IEC, 2005. Version 1.4. Release 2005/09/11.&lt;/xs:documentation&gt;
        ///	&lt;/xs:annotation&gt;
        ///	&lt;xs:include schemaLoca [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string scl {
            get {
                return ResourceManager.GetString("scl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.iec.ch/61850/2003/SCL&quot; xmlns=&quot;http://www.iec.ch/61850/2003/SCL&quot;
        ///	xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;
        ///	version=&quot;1.4&quot;&gt;
        ///	&lt;xs:annotation&gt;
        ///		&lt;xs:documentation xml:lang=&quot;en&quot;&gt;COPYRIGHT IEC, 2005. Version 1.4. Release
        ///2005/09/11.&lt;/xs:documentation&gt;
        ///	&lt;/xs:annotation&gt;
        ///	&lt;xs:simpleType name=&quot;tRef&quot;&gt;
        ///		&lt;xs:restriction base=&quot;xs:normalizedString&quot;&gt;
        ///			&lt;xs:pattern  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string scl_basesimpletypes {
            get {
                return ResourceManager.GetString("scl_basesimpletypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.iec.ch/61850/2003/SCL&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	xmlns=&quot;http://www.iec.ch/61850/2003/SCL&quot; xmlns:scl=&quot;http://www.iec.ch/61850/2003/SCL&quot; elementFormDefault=&quot;qualified&quot;
        ///	attributeFormDefault=&quot;unqualified&quot; version=&quot;1.4&quot;&gt;
        ///	&lt;xs:annotation&gt;
        ///		&lt;xs:documentation xml:lang=&quot;en&quot;&gt;COPYRIGHT IEC, 2005. Version 1.4. Release 2005/09/11.&lt;/xs:documentation&gt;
        ///	&lt;/xs:annotation&gt;
        ///	&lt;xs:include schemaLocation=&quot;SCL_Enums.xsd&quot; /&gt;
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string scl_basetypes {
            get {
                return ResourceManager.GetString("scl_basetypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.iec.ch/61850/2003/SCL&quot; xmlns=&quot;http://www.iec.ch/61850/2003/SCL&quot;
        ///	xmlns:scl=&quot;http://www.iec.ch/61850/2003/SCL&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; version=&quot;1.4&quot;&gt;
        ///	&lt;xs:annotation&gt;
        ///		&lt;xs:documentation xml:lang=&quot;en&quot;&gt;COPYRIGHT IEC, 2005. Version 1.4. Release 2005/09/11.&lt;/xs:documentation&gt;
        ///	&lt;/xs:annotation&gt;
        ///	&lt;xs:include schemaLocation=&quot;SCL_BaseTypes.xsd&quot;  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string SCL_Communication {
            get {
                return ResourceManager.GetString("SCL_Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;xs:schema xmlns=&quot;http://www.iec.ch/61850/2003/SCLcoordinates&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.iec.ch/61850/2003/SCLcoordinates&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; version=&quot;0.1&quot;&gt;
        ///	&lt;xs:annotation&gt;
        ///		&lt;xs:documentation xml:lang=&quot;en&quot;&gt;Version 1.0. Release 2003/09/19.This schema is for infomational purposes only, and is not normative!&lt;/xs:documentation&gt;
        ///	&lt;/xs:annotation&gt;
        ///	&lt;xs:simpleType name=&quot;tConndir&quot;&gt;
        ///		&lt;xs:restriction base=&quot;xs:normaliz [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string scl_coordinates {
            get {
                return ResourceManager.GetString("scl_coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.iec.ch/61850/2003/SCL&quot; xmlns=&quot;http://www.iec.ch/61850/2003/SCL&quot;
        ///	xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:scl=&quot;http://www.iec.ch/61850/2003/SCL&quot;
        ///	elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; version=&quot;1.4&quot;&gt;
        ///	&lt;xs:annotation&gt;
        ///		&lt;xs:documentation xml:lang=&quot;en&quot;&gt;COPYRIGHT IEC, 2005. Version 1.4. Release 2005/09/11.&lt;/xs:documentation&gt;
        ///	&lt;/xs:annotation&gt;
        ///	&lt;xs:include schemaLocation=&quot;SCL_BaseTypes.xsd&quot;  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string SCL_DataTypeTemplates {
            get {
                return ResourceManager.GetString("SCL_DataTypeTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.iec.ch/61850/2003/SCL&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	xmlns=&quot;http://www.iec.ch/61850/2003/SCL&quot; xmlns:scl=&quot;http://www.iec.ch/61850/2003/SCL&quot; elementFormDefault=&quot;qualified&quot;
        ///	attributeFormDefault=&quot;unqualified&quot; version=&quot;1.4&quot;&gt;
        ///	&lt;xs:annotation&gt;
        ///		&lt;xs:documentation xml:lang=&quot;en&quot;&gt;COPYRIGHT IEC, 2005. Version 1.4. Release 2005/09/11.&lt;/xs:documentation&gt;
        ///	&lt;/xs:annotation&gt;
        ///	&lt;xs:include schemaLocation=&quot;SCL_BaseSimpleTypes [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string scl_enums {
            get {
                return ResourceManager.GetString("scl_enums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.iec.ch/61850/2003/SCL&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.iec.ch/61850/2003/SCL&quot; xmlns:scl=&quot;http://www.iec.ch/61850/2003/SCL&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; version=&quot;1.4&quot;&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation xml:lang=&quot;en&quot;&gt;COPYRIGHT IEC, 2005. Version 1.4. Release 2005/09/11.&lt;/xs:documentation&gt;
        ///  &lt;/xs:annotation&gt;
        ///  &lt;xs:include schemaLocation=&quot;SCL_BaseTypes.xsd&quot;  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string SCL_IED {
            get {
                return ResourceManager.GetString("SCL_IED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.iec.ch/61850/2003/SCLmaintenance&quot; targetNamespace=&quot;http://www.iec.ch/61850/2003/SCLmaintenance&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; version=&quot;1.0&quot;&gt;
        ///	&lt;xs:annotation&gt;
        ///		&lt;xs:documentation xml:lang=&quot;en&quot;&gt;Version 1.0. Release 2003/08/28.This schema is for infomational purposes only, and is not normative!&lt;/xs:documentation&gt;
        ///	&lt;/xs:annotation&gt;
        ///	&lt;xs:simpleType name=&quot;tRestrN [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string scl_maintenance {
            get {
                return ResourceManager.GetString("scl_maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.iec.ch/61850/2003/SCL&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.iec.ch/61850/2003/SCL&quot; xmlns:scl=&quot;http://www.iec.ch/61850/2003/SCL&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; version=&quot;1.4&quot;&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation xml:lang=&quot;en&quot;&gt;COPYRIGHT IEC, 2005. Version 1.4. Release 2005/09/11.&lt;/xs:documentation&gt;
        ///  &lt;/xs:annotation&gt;
        ///  &lt;xs:include schemaLocation=&quot;SCL_BaseTypes.xsd&quot;  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string SCL_Substation {
            get {
                return ResourceManager.GetString("SCL_Substation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:scl=&quot;http://www.iec.ch/61850/2003/SCL&quot; xmlns=&quot;http://www.iec.ch/61850/2003/SCL&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.iec.ch/61850/2003/SCL&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; finalDefault=&quot;extension&quot; version=&quot;1.0&quot;&gt;
        ///	&lt;xs:annotation&gt;
        ///		&lt;xs:documentation xml:lang=&quot;en&quot;&gt;Release 2003/09/19.
        ///	    This schema is for infomational purposes only, and is not normative!
        ///	    Notes:
        ///	    - Ident [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string sclvariants {
            get {
                return ResourceManager.GetString("sclvariants", resourceCulture);
            }
        }
    }
}
