//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISC.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LastOpenedFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LastOpenedFiles"]));
            }
            set {
                this["LastOpenedFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LastConnectedIpAddress {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LastConnectedIpAddress"]));
            }
            set {
                this["LastConnectedIpAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastProjectPath {
            get {
                return ((string)(this["LastProjectPath"]));
            }
            set {
                this["LastProjectPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LastIpAddresses {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LastIpAddresses"]));
            }
            set {
                this["LastIpAddresses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LastConnectedFTPIpAddreses {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LastConnectedFTPIpAddreses"]));
            }
            set {
                this["LastConnectedFTPIpAddreses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAutoEnabledQualityInGooseReceiving {
            get {
                return ((bool)(this["IsAutoEnabledQualityInGooseReceiving"]));
            }
            set {
                this["IsAutoEnabledQualityInGooseReceiving"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAutoEnabledValidityInGooseReceiving {
            get {
                return ((bool)(this["IsAutoEnabledValidityInGooseReceiving"]));
            }
            set {
                this["IsAutoEnabledValidityInGooseReceiving"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MmsQueryDelay {
            get {
                return ((int)(this["MmsQueryDelay"]));
            }
            set {
                this["MmsQueryDelay"] = value;
            }
        }
    }
}
