//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISC.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LastOpenedFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LastOpenedFiles"]));
            }
            set {
                this["LastOpenedFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LastConnectedIpAddress {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LastConnectedIpAddress"]));
            }
            set {
                this["LastConnectedIpAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastProjectPath {
            get {
                return ((string)(this["LastProjectPath"]));
            }
            set {
                this["LastProjectPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LastIpAddresses {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LastIpAddresses"]));
            }
            set {
                this["LastIpAddresses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LastConnectedFTPIpAddreses {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LastConnectedFTPIpAddreses"]));
            }
            set {
                this["LastConnectedFTPIpAddreses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAutoEnabledQualityInGooseReceiving {
            get {
                return ((bool)(this["IsAutoEnabledQualityInGooseReceiving"]));
            }
            set {
                this["IsAutoEnabledQualityInGooseReceiving"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAutoEnabledValidityInGooseReceiving {
            get {
                return ((bool)(this["IsAutoEnabledValidityInGooseReceiving"]));
            }
            set {
                this["IsAutoEnabledValidityInGooseReceiving"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MmsQueryDelay {
            get {
                return ((int)(this["MmsQueryDelay"]));
            }
            set {
                this["MmsQueryDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsUserLoggingEnabled {
            get {
                return ((bool)(this["IsUserLoggingEnabled"]));
            }
            set {
                this["IsUserLoggingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int FtpTimeOutDelay {
            get {
                return ((int)(this["FtpTimeOutDelay"]));
            }
            set {
                this["FtpTimeOutDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int MaxResponseTime {
            get {
                return ((int)(this["MaxResponseTime"]));
            }
            set {
                this["MaxResponseTime"] = value;
            }
        }
    }
}
